### PR TITLE
ORD logo version 1

### PR DESCRIPTION
**Pull request by norro**
Pretty simple and straightforward. Feedback welcome!

Signed-off-by: Arne Nordmann (CR/AEA2) <arne.nordmann@de.bosch.com>

### CODE REVIEW

**Comment by joernmalzahn** [comment]
I really like the idea of making the database symbol a the core part of the logo. Not sure, if the arm and the gripper are too small. I do not recognize the thing on the bottom left. 🤔

**Comment by joernmalzahn** [comment]
so, number 3 is out, still simplistic, but "open and database". would be nice to also have something "robotique"

**Comment by norro** [comment]
I like the idea. I will go for another iteration

**Comment by norro** [comment]
@joernmalzahn go!

**Comment by joernmalzahn** [comment]
Pure beauty!

**Pull request merged**
